/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhir;

import TugasAkhir.KoneksiKashoes;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class MasterOrder extends javax.swing.JFrame {

    public static Connection cn;
    public static ResultSet rs;
    public static Statement st;
    public static PreparedStatement pst;

    /**
     * Creates new form MasterOrder
     */
    public MasterOrder() {
        initComponents();
        setExtendedState(MasterOrder.MAXIMIZED_BOTH);
        txtTransaksi.setText(generate_id());
        txtTransaksiDetil.setText(generate_idDet());
        table();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelDet = new javax.swing.JTable();
        btsimpan = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        bttambah = new javax.swing.JButton();
        txtTransaksi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTransaksiDetil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBahan = new javax.swing.JTextField();
        Bersih = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("ID Transaksi");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabel.setBackground(new java.awt.Color(35, 19, 90));
        Tabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        Tabel.setForeground(new java.awt.Color(255, 255, 255));
        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 75, 970, 350));

        TabelDet.setBackground(new java.awt.Color(35, 19, 90));
        TabelDet.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        TabelDet.setForeground(new java.awt.Color(255, 255, 255));
        TabelDet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TabelDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDetMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelDet);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 75, 950, 350));

        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, -1, -1));

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        getContentPane().add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, -1, -1));

        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });
        getContentPane().add(bttambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, -1, -1));

        txtTransaksi.setEnabled(false);
        txtTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(txtTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, 110, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 800, -1, -1));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 800, 110, -1));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jumlah");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 840, -1, -1));

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 840, 110, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. Telephone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 880, -1, -1));
        getContentPane().add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 880, 110, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 640, -1, -1));

        txtTransaksiDetil.setEnabled(false);
        txtTransaksiDetil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransaksiDetilActionPerformed(evt);
            }
        });
        getContentPane().add(txtTransaksiDetil, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 690, 110, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Transaksi Detail");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 690, -1, -1));

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(5);
        jScrollPane3.setViewportView(txtKeterangan);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 640, 292, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Keterangan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 640, -1, -1));

        txtKode.setEnabled(false);
        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 770, 110, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kode Paket");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 770, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bahan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 640, -1, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 820, 77, -1));

        jLabel11.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Harga");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 820, -1, -1));

        txtBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBahanActionPerformed(evt);
            }
        });
        getContentPane().add(txtBahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 640, 130, -1));

        Bersih.setText("Bersih");
        Bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihActionPerformed(evt);
            }
        });
        getContentPane().add(Bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 450, -1, -1));

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pegawai/gambar/management/bg manajemen.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // Get the selected row index
        int row = Tabel.getSelectedRow();
        int rowdet = TabelDet.getSelectedRow();
        if (row < 0 && rowdet < 0) {
            // No row is selected, show an error message
            JOptionPane.showMessageDialog(null, "Pilih data yang akan diubah");
            return;
        }
        try {
            if (row >= 0) {
                // tabel transaksi
                String id_transaksi_pk = Tabel.getValueAt(row, 0).toString();
                String nama = Tabel.getValueAt(row, 1).toString();
                String no_telp = Tabel.getValueAt(row, 2).toString();
                String jml_sepatu = Tabel.getValueAt(row, 3).toString();
                String total_bayar = Tabel.getValueAt(row, 4).toString();
                // Connect
                cn = KoneksiKashoes.koneksikashoesdB();

                // Set the parameter values
                String sql = "UPDATE transaksi SET nama = ?, no_telp = ?, jml_sepatu = ?, total_bayar = ? WHERE id_transaksi = ?";
                pst = cn.prepareStatement(sql);
                pst.setString(1, nama);
                pst.setString(2, no_telp);
                pst.setString(3, jml_sepatu);
                pst.setString(4, total_bayar);
                pst.setString(5, id_transaksi_pk);
                // Execute the statement
                pst.executeUpdate();
            }
            if (rowdet >= 0) {
                // tabel transaksi detil
                String id_transaksidetil = TabelDet.getValueAt(row, 0).toString();
                String id_transaksi_fk = TabelDet.getValueAt(row, 1).toString();
                String id_paket = TabelDet.getValueAt(row, 2).toString();
                String bahan = TabelDet.getValueAt(row, 3).toString();
                String keterangan = TabelDet.getValueAt(row, 4).toString();
                String tanggal = TabelDet.getValueAt(row, 5).toString();
                // Connect
                cn = KoneksiKashoes.koneksikashoesdB();

                // Set the parameter values
                String sqldet = "UPDATE transaksi_detil SET id_transaksi = ?, id_paket = ?, bahan = ?, keterangan = ?, tanggal = ? WHERE id_transaksidetil = ?";
                pst = cn.prepareStatement(sqldet);
                pst.setString(1, id_transaksi_fk);
                pst.setString(2, id_paket);
                pst.setString(3, bahan);
                pst.setString(4, keterangan);
                pst.setString(5, tanggal);
                pst.setString(6, id_transaksidetil);
                // Execute the statement
                pst.executeUpdate();

            }
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal mengubah data: " + e.getMessage());
        }
        // Update table
        table();
        clear();
    }//GEN-LAST:event_btsimpanActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        hapus();
        table();
        clear();
    }//GEN-LAST:event_bthapusActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // TODO add your handling code here:
        tambah();
        table();
        clear();
    }//GEN-LAST:event_bttambahActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        int bar = Tabel.getSelectedRow();
        String a = Tabel.getValueAt(bar, 0).toString();
        String b = Tabel.getValueAt(bar, 1).toString();
        String c = Tabel.getValueAt(bar, 2).toString();
        String d = Tabel.getValueAt(bar, 3).toString();
        String e = Tabel.getValueAt(bar, 4).toString();

        txtTransaksi.setText(a);
        txtNama.setText(b);
        txtJumlah.setText(c);
        txtTelephone.setText(d);
        txtTotal.setText(e);
        TabelDet.setRowSelectionInterval(bar, bar);
        TabelDet.scrollRectToVisible(TabelDet.getCellRect(bar, 0, true));
    }//GEN-LAST:event_TabelMouseClicked

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransaksiActionPerformed

    private void txtTransaksiDetilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransaksiDetilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransaksiDetilActionPerformed

    private void TabelDetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDetMouseClicked
        // TODO add your handling code here:
        int bar = TabelDet.getSelectedRow();
        String a = TabelDet.getValueAt(bar, 0).toString();
        String b = TabelDet.getValueAt(bar, 1).toString();
        String c = TabelDet.getValueAt(bar, 2).toString();
        String d = TabelDet.getValueAt(bar, 3).toString();
        String e = TabelDet.getValueAt(bar, 4).toString();

        txtTransaksiDetil.setText(a);
        txtTransaksi.setText(b);
        txtKode.setText(c);
        txtBahan.setText(d);
        txtKeterangan.setText(e);
        Tabel.setRowSelectionInterval(bar, bar);
        Tabel.scrollRectToVisible(Tabel.getCellRect(bar, 0, true));
    }//GEN-LAST:event_TabelDetMouseClicked

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    private void txtBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBahanActionPerformed

    private void BersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_BersihActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        new Order().setVisible(true);
        dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    public String generate_id() {
        int row = 0;
        try {
            String sql = "SELECT COUNT(*) FROM transaksi";
            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                row = rs.getInt(1);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
        }
        String id = "TR" + String.valueOf(row + 1);

        return id;
    }

    public String generate_idDet() {
        int row = 0;
        try {
            String sql = "SELECT COUNT(*) FROM transaksi_detil";
            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                row = rs.getInt(1);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
        }
        String iddet = "TRD" + String.valueOf(row + 1);

        return iddet;
    }

    private void tambah() {
        try {

            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();

            pst = cn.prepareStatement("INSERT INTO transaksi (id_transaksi,nama,no_telp,jml_sepatu,total_bayar) VALUES(?,?,?,?,?)");

            pst.setString(1, txtTransaksi.getText());
            pst.setString(2, txtNama.getText());
            pst.setString(3, txtJumlah.getText());
            pst.setString(4, txtTelephone.getText());
            pst.setString(5, txtTotal.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Masukan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menambahkan data: " + e.getMessage());
        }
    }

    private void table() {
        DefaultTableModel tbl = new DefaultTableModel(), tblDet = new DefaultTableModel();
        tbl.addColumn("ID Transaksi");
        tbl.addColumn("Nama");
        tbl.addColumn("Telephone");
        tbl.addColumn("Jumlah");
        tbl.addColumn("Total Harga");
        tblDet.addColumn("ID Transaksi Detil");
        tblDet.addColumn("ID Transaksi");
        tblDet.addColumn("ID Paket");
        tblDet.addColumn("Bahan");
        tblDet.addColumn("Keterangan");
        tblDet.addColumn("Tanggal");

        String sql_data = "SELECT * FROM transaksi ORDER BY id_transaksi ASC";

        String sql_dataDet = "SELECT * FROM transaksi_detil ORDER BY id_transaksidetil ASC";

        //tabel transaksi
        try {
            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();
            rs = st.executeQuery(sql_data);
            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("id_transaksi"),
                    rs.getString("nama"),
                    rs.getString("no_telp"),
                    rs.getString("jml_sepatu"),
                    rs.getString("total_bayar")
                });
            }
            Tabel.setModel(tbl);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        //tabel transaksi detil
        try {
            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();
            rs = st.executeQuery(sql_dataDet);
            while (rs.next()) {
                tblDet.addRow(new Object[]{
                    rs.getString("id_transaksidetil"),
                    rs.getString("id_transaksi"),
                    rs.getString("id_paket"),
                    rs.getString("bahan"),
                    rs.getString("keterangan"),
                    rs.getString("tanggal")
                });
            }

            TabelDet.setModel(tblDet);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void clear() {
        txtTransaksi.setText("");
        txtNama.setText("");
        txtJumlah.setText("");
        txtTelephone.setText("");
        txtTransaksiDetil.setText("");
        txtTransaksi.setText("");
        txtKode.setText("");
        txtBahan.setText("");
        txtKeterangan.setText("");
        table();
    }

    private void hapus() {
        int update = JOptionPane.showOptionDialog(this, "apakah yakin hapus data?", "Hapus Data",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (update == JOptionPane.YES_OPTION) {
            try {
                cn = KoneksiKashoes.koneksikashoesdB();
                st = cn.createStatement();
                String sql_del = "DELETE from transaksi WHERE id_transaksi='" + txtTransaksi.getText() + "'";
                st.execute(sql_del);
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
                table();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            clear();
        }
    }
//     private void cari() {
//         DefaultTableModel model = new DefaultTableModel();
//         int row = model.getRowCount();
//         for (int c = 0; c < row; c++) {
//             model.removeRow(0);
//         }
//         
//         String cari = txtcari.getText();
//    String query = "SELECT * FROM tbpertama WHERE nim LIKE '%" + cari + "%' OR nama LIKE '%" + cari + "%'";
//
//    try {
//        Connection connect = coneksi.koneksidB();
//        Statement sttmnt = connect.createStatement();
//        ResultSet rslt = sttmnt.executeQuery(query);
//
//        while (rslt.next()) {
//            String d1 = rslt.getString("nim");
//            String d2 = rslt.getString("nama");
//            String d3 = rslt.getString("alamat");
//            String d4 = rslt.getString("tgl_lahir");
//            String d5 = rslt.getString("jmlh_saudara");
//            String d6 = rslt.getString("ipk");
//
//            String a = rslt.getString("nim");
//            String b = rslt.getString("nama");
//            String c = rslt.getString("alamat");
//            String d = rslt.getString("tgl_lahir");
//            String e = rslt.getString("jmlh_saudara");
//            String f = rslt.getString("ipk");
//
//            txtnim.setText(a);
//            txtnama.setText(b);
//            txtalamat.setText(c);
//            txttgl.setText(d);
//            txtsau.setText(e);
//            txtipk.setText(f);
//
//            String[] data = {d1, d2, d3, d4, d5, d6};
//            model.addRow(data);
//        }
//    } catch (Exception e) {
//        System.out.println(e);
//    }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bersih;
    private javax.swing.JButton Kembali;
    public javax.swing.JTable Tabel;
    private javax.swing.JTable TabelDet;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton bttambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextField txtBahan;
    public javax.swing.JTextField txtJumlah;
    public javax.swing.JTextArea txtKeterangan;
    public javax.swing.JTextField txtKode;
    public javax.swing.JTextField txtNama;
    public javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtTransaksi;
    public javax.swing.JTextField txtTransaksiDetil;
    // End of variables declaration//GEN-END:variables
}
