/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package master;

import TugasAkhir.KoneksiKashoes;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import transaksi.Order;

/**
 *
 * @author LENOVO
 */
public class MasterOrder extends javax.swing.JFrame {

    public static Connection cn;
    public static ResultSet rs;
    public static Statement st;
    public static PreparedStatement pst;

    /**
     * Creates new form MasterOrder
     */
    public MasterOrder() {
        initComponents();
        setExtendedState(MasterOrder.MAXIMIZED_BOTH);
        txtTransaksi.setText(generate_id());
        txtTransaksiDetil.setText(generate_idDet());
        table();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldet = new javax.swing.JTable();
        btsimpan = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        bttambah = new javax.swing.JButton();
        txtTransaksi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTransaksiDetil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBahan = new javax.swing.JTextField();
        Bersih = new javax.swing.JButton();
        txtTanggal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("ID Transaksi");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 590, 245));

        tabeldet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabeldet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldetMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeldet);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 280, 620, 245));

        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 530, -1, -1));

        bthapus.setText("hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        getContentPane().add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 530, -1, -1));

        bttambah.setText("tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });
        getContentPane().add(bttambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 530, -1, -1));

        txtTransaksi.setEnabled(false);
        txtTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(txtTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, 110, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 680, -1, -1));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 680, 110, -1));

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel9.setText("Jumlah");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 710, -1, -1));

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 710, 110, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel7.setText("No. Telephone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 740, -1, -1));
        getContentPane().add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 740, 110, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel2.setText("ID Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, -1, -1));

        txtTransaksiDetil.setEnabled(false);
        txtTransaksiDetil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransaksiDetilActionPerformed(evt);
            }
        });
        getContentPane().add(txtTransaksiDetil, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 650, 110, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel3.setText("ID Transaksi Detail");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 650, -1, -1));

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(5);
        jScrollPane3.setViewportView(txtKeterangan);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 620, 420, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel8.setText("Keterangan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 620, -1, -1));

        txtKode.setEnabled(false);
        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 720, 100, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel5.setText("Kode Paket");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 720, -1, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 760, 80, -1));

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel11.setText("Total Harga");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 760, -1, -1));

        txtBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBahanActionPerformed(evt);
            }
        });
        getContentPane().add(txtBahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 620, 94, -1));

        Bersih.setText("Bersih");
        Bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihActionPerformed(evt);
            }
        });
        getContentPane().add(Bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 530, -1, -1));
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 720, 100, -1));

        jLabel12.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Customer Order");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master/gambar/Group 83 (1).png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        jLabel14.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Management Order");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master/gambar/Group 84 (1).png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 100, -1));

        txtCari.setEditable(false);
        txtCari.setBackground(new java.awt.Color(35, 25, 87));
        txtCari.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtCari.setForeground(new java.awt.Color(255, 255, 255));
        txtCari.setText("Cari");
        txtCari.setBorder(null);
        txtCari.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCariFocusLost(evt);
            }
        });
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 60, 400, 40));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi/gambar/Rectangle 90.png"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 60, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi/gambar/Vector (1).png"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 60, -1, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi/gambar/Group 82.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi/gambar/Group 81.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        edit();
        table();
        clearMO();
    }//GEN-LAST:event_btsimpanActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        hapus();
        table();
        clearMO();
    }//GEN-LAST:event_bthapusActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // TODO add your handling code here:
        tambah();
        table();
        clearMO();
    }//GEN-LAST:event_bttambahActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        int bar = Tabel.getSelectedRow();
        String a = Tabel.getValueAt(bar, 0).toString();
        String b = Tabel.getValueAt(bar, 1).toString();
        String c = Tabel.getValueAt(bar, 2).toString();
        String d = Tabel.getValueAt(bar, 3).toString();
        String e = Tabel.getValueAt(bar, 4).toString();

        txtTransaksi.setText(a);
        txtNama.setText(b);
        txtJumlah.setText(c);
        txtTelephone.setText(d);
        txtTotal.setText(e);
        
    }//GEN-LAST:event_TabelMouseClicked

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransaksiActionPerformed

    private void txtTransaksiDetilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransaksiDetilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransaksiDetilActionPerformed

    private void tabeldetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldetMouseClicked
        // TODO add your handling code here:
        int bar = tabeldet.getSelectedRow();
        String a = tabeldet.getValueAt(bar, 0).toString();
        String b = tabeldet.getValueAt(bar, 1).toString();
        String c = tabeldet.getValueAt(bar, 2).toString();
        String d = tabeldet.getValueAt(bar, 3).toString();
        String e = tabeldet.getValueAt(bar, 4).toString();
        String f = tabeldet.getValueAt(bar, 5).toString();

        txtTransaksiDetil.setText(a);
        txtTransaksi.setText(b);
        txtKode.setText(c);
        txtBahan.setText(d);
        txtKeterangan.setText(e);
        txtTanggal.setText(f);
    }//GEN-LAST:event_tabeldetMouseClicked

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    private void txtBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBahanActionPerformed

    private void BersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihActionPerformed
        // TODO add your handling code here:
        clearMO();
    }//GEN-LAST:event_BersihActionPerformed

    private void txtCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariFocusGained
        // TODO add your handling code here:
        if (txtCari.getText().equals("Cari")){
            txtCari.setText("");
        }
    }//GEN-LAST:event_txtCariFocusGained

    private void txtCariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariFocusLost
        // TODO add your handling code here:
        if (txtCari.getText().isBlank()){
            txtCari.setText("Cari");
        }
    }//GEN-LAST:event_txtCariFocusLost

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        new Order().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        new Order().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    public String generate_id() {
        int row = 0;
        try {
            String sql = "SELECT COUNT(*) FROM transaksi";
            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                row = rs.getInt(1);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
        }
        String id = "TR" + String.valueOf(row + 1);

        return id;
    }

    public String generate_idDet() {
        int row = 0;
        try {
            String sql = "SELECT COUNT(*) FROM transaksi_detil";
            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                row = rs.getInt(1);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
        }
        String iddet = "TRD" + String.valueOf(row + 1);

        return iddet;
    }

    private void tambah() {
        try {

            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();

            pst = cn.prepareStatement("INSERT INTO transaksi (id_transaksi,nama,no_telp,jml_sepatu,total_bayar) VALUES(?,?,?,?,?)");

            pst.setString(1, txtTransaksi.getText());
            pst.setString(2, txtNama.getText());
            pst.setString(3, txtJumlah.getText());
            pst.setString(4, txtTelephone.getText());
            pst.setString(5, txtTotal.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Masukan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menambahkan data: " + e.getMessage());
        }
    }

    private void table() {
        DefaultTableModel tbl = new DefaultTableModel(), tblDet = new DefaultTableModel();
        tbl.addColumn("ID Transaksi");
        tbl.addColumn("Nama");
        tbl.addColumn("Telephone");
        tbl.addColumn("Jumlah");
        tbl.addColumn("Total Harga");
        tblDet.addColumn("ID Transaksi Detil");
        tblDet.addColumn("ID Transaksi");
        tblDet.addColumn("ID Paket");
        tblDet.addColumn("Bahan");
        tblDet.addColumn("Keterangan");
        tblDet.addColumn("Tanggal");

        String sql_data = "SELECT * FROM transaksi ORDER BY id_transaksi ASC";

        String sql_dataDet = "SELECT * FROM transaksi_detil ORDER BY id_transaksidetil ASC";

        //tabel transaksi
        try {
            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();
            rs = st.executeQuery(sql_data);
            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("id_transaksi"),
                    rs.getString("nama"),
                    rs.getString("no_telp"),
                    rs.getString("jml_sepatu"),
                    rs.getString("total_bayar")
                });
            }
            Tabel.setModel(tbl);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        //tabel transaksi detil
        try {
            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();
            rs = st.executeQuery(sql_dataDet);
            while (rs.next()) {
                tblDet.addRow(new Object[]{
                    rs.getString("id_transaksidetil"),
                    rs.getString("id_transaksi"),
                    rs.getString("id_paket"),
                    rs.getString("bahan"),
                    rs.getString("keterangan"),
                    rs.getString("tanggal")
                });
            }

            tabeldet.setModel(tblDet);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void clearMO() {
        txtTransaksi.setText("");
        txtNama.setText("");
        txtJumlah.setText("");
        txtTelephone.setText("");
        txtTransaksiDetil.setText("");
        txtTransaksi.setText("");
        txtKode.setText("");
        txtBahan.setText("");
        txtKeterangan.setText("");
        txtCari.setText("Cari");
        txtTotal.setText("");
        table();
    }

    private void edit() {
        try {
            cn = KoneksiKashoes.koneksikashoesdB();
            st = cn.createStatement();

            String sql_up = "UPDATE transaksi SET nama='" + txtNama.getText()
                    + "',jml_sepatu='" + txtJumlah.getText()
                    + "',no_telp='" + txtTelephone.getText()
                    + "' WHERE id_transaksi='" + txtTransaksi.getText() + "'";

            st.execute(sql_up);
            JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void hapus() {
        int update = JOptionPane.showOptionDialog(this, "apakah yakin hapus data?", "Hapus Data",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (update == JOptionPane.YES_OPTION) {
            try {
                cn = KoneksiKashoes.koneksikashoesdB();
                st = cn.createStatement();
                String sql_del = "DELETE from transaksi WHERE id_transaksi='" + txtTransaksi.getText() + "'";
                st.execute(sql_del);
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
                table();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            clearMO();
        }
    }
     private void cari() {
         DefaultTableModel model = new DefaultTableModel();
         int row = model.getRowCount();
         for (int c = 0; c < row; c++) {
             model.removeRow(0);
         }
         
         String cari = txtCari.getText();
    String query = "SELECT * FROM transaksi WHERE id_transaksi LIKE '%" + cari + "%' OR nama LIKE '%" + cari + "%'";
    String queryDet = "SELECT * FROM transaksi_detil WHERE id_transaksidetil LIKE '%" + cari + "%' OR tanggal LIKE '%" + cari + "%'";
    
        try {
            Connection connect = KoneksiKashoes.koneksikashoesdB();
            Statement sttmnt = connect.createStatement();
            ResultSet rslt = sttmnt.executeQuery(query);

            while (rslt.next()) {
                String d1 = rslt.getString("id_transaksi");
                String d2 = rslt.getString("nama");
                String d3 = rslt.getString("no_telp");
                String d4 = rslt.getString("jml_sepatu");
                String d5 = rslt.getString("total_bayar");

                String a = rslt.getString("id_transaksi");
                String b = rslt.getString("nama");
                String c = rslt.getString("no_telp");
                String d = rslt.getString("jml_sepatu");
                String e = rslt.getString("total_bayar");

                txtTransaksi.setText(a);
                txtNama.setText(b);
                txtTelephone.setText(c);
                txtJumlah.setText(d);
                txtTotal.setText(e);


                String[] data = {d1, d2, d3, d4, d5};
                model.addRow(data);
            }
        }catch (Exception e) {
        System.out.println(e);
    }

    try {
        Connection connect = KoneksiKashoes.koneksikashoesdB();
        Statement sttmnt = connect.createStatement();
        ResultSet rslt = sttmnt.executeQuery(queryDet);

        while (rslt.next()) {
            String d1 = rslt.getString("id_transaksidetil");
            String d2 = rslt.getString("id_transaksi");
            String d3 = rslt.getString("id_paket");
            String d4 = rslt.getString("bahan");
            String d5 = rslt.getString("keterangan");
            String d6 = rslt.getString("tanggal");
            
            String a = rslt.getString("id_transaksidetil");
            String b = rslt.getString("id_transaksi");
            String c = rslt.getString("id_paket");
            String d = rslt.getString("bahan");
            String e = rslt.getString("keterangan");
            String f = rslt.getString("tanggal");
            
            txtTransaksiDetil.setText(a);
            txtTransaksi.setText(b);
            txtKode.setText(c);
            txtBahan.setText(d);
            txtKeterangan.setText(e);
            txtTanggal.setText(f);
            

            String[] data = {d1, d2, d3, d4, d5,d6};
            model.addRow(data);
        }
    } catch (Exception e) {
        System.out.println(e);
    }
    }
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bersih;
    public javax.swing.JTable Tabel;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton bttambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabeldet;
    public javax.swing.JTextField txtBahan;
    private javax.swing.JTextField txtCari;
    public javax.swing.JTextField txtJumlah;
    public javax.swing.JTextArea txtKeterangan;
    public javax.swing.JTextField txtKode;
    public javax.swing.JTextField txtNama;
    public javax.swing.JTextField txtTanggal;
    public javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtTransaksi;
    public javax.swing.JTextField txtTransaksiDetil;
    // End of variables declaration//GEN-END:variables
}
